// Opciones predefinidas para los formularios del sistema

export const DEPARTAMENTOS = [
  'Informática',
  'Contabilidad',
  'Recursos Humanos',
  'Administración',
  'Dirección',
  'Ventas',
  'Marketing',
  'Atención al Cliente',
  'Operaciones',
  'Legal',
  'Otro',
]

export const UBICACIONES = [
  'Oficina Principal',
  'Oficina Secundaria',
  'Sala de Reuniones',
  'Almacén',
  'Laboratorio',
  'Taller',
  'Otra',
]

export const RACKS_PREDEFINIDOS = [
  'Rack-01',
  'Rack-02',
  'Rack-03',
  'Rack-04',
  'Rack-05',
  'Rack-A',
  'Rack-B',
  'Rack-C',
  'Switch-01',
  'Switch-02',
  'Switch-03',
  'Router Principal',
  'Router Secundario',
]

export const MARCAS_COMPONENTES = {
  CPU: [
    'VIT',
    'Dell',
    'HP',
    'Lenovo',
    'Acer',
    'ASUS',
    'Apple',
    'Microsoft',
    'Intel',
    'AMD',
    'Otro',
  ],
  Monitor: [
    'VIT',
    'LG',
    'Samsung',
    'Dell',
    'HP',
    'Acer',
    'ASUS',
    'BenQ',
    'ViewSonic',
    'AOC',
    'Philips',
    'Otro',
  ],
  Teclado: [
    'VIT',
    'Logitech',
    'Microsoft',
    'Dell',
    'HP',
    'IBM',
    'Corsair',
    'Razer',
    'SteelSeries',
    'Otro',
  ],
  Mouse: [
    'VIT',
    'Logitech',
    'Microsoft',
    'Dell',
    'HP',
    'Razer',
    'Corsair',
    'SteelSeries',
    'PHILIPS',
    'Otro',
  ],
}

// Modelos comunes por marca (para autocompletar)
export const MODELOS_POR_MARCA: Record<string, string[]> = {
  'VIT': [
    'VITE-1210-01',
    'VIT-E210-001',
    'VITE1210-01',
    'VIT2810-02',
    'VIT-2810-02',
    'VIT28110-2',
    'VIT-E1210-01',
    'Vit-E1210-01',
    'VIT-2811002',
    'TFT19W80PS',
    'TFT19W80P3',
    'TFT19W80P5',
    '1901-M00006',
    '19DMT620AMLUNN2',
    'DOK-K5313',
    'DOK-R5313',
    'KB2971',
    'KB-2971',
    'DOK-M696',
    'VC066',
  ],
  'LG': [
    'W19425T',
    '22MP58',
    '24MP59G',
    '27MP59G',
    '27GL850',
    '32UN650',
  ],
  'Samsung': [
    'LS16CMYSFUZM',
    'F390',
    'T350',
    'C27F390',
    'Odyssey G5',
  ],
  'Dell': [
    'OptiPlex 7090',
    'OptiPlex 3090',
    'Latitude 5520',
    'P2419H',
    'U2720Q',
  ],
  'HP': [
    'EliteDesk 800',
    'ProDesk 600',
    'Z27',
    'Pavilion',
  ],
  'IBM': [
    'KB0225',
    'ThinkPad',
  ],
  'Logitech': [
    'MX Master 3',
    'MX Keys',
    'K380',
    'M705',
  ],
  'Microsoft': [
    'Surface Keyboard',
    'Surface Mouse',
    'Wireless Desktop',
  ],
}

